import type { Metadata } from "next";
import "@/style/index.css";
import LayoutPage from "@/components/layout/LayoutPage";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutPage>
          <div className="w-full text-white   flex flex-col bg-menu  ">
            {children}
          </div>
        </LayoutPage>
      </body>
    </html>
  );
}
