import type { Metadata } from "next";
import "@/style/index.scss";
import { AuthProvider } from "@/contexts/AuthContext";
import { AxiosProvider } from "@/providers/AxiosProvider";
import CustomQueryClientProvider from "@/providers/QueryClientProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <AxiosProvider>
            <CustomQueryClientProvider>{children}</CustomQueryClientProvider>
          </AxiosProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
