import type { Metadata } from "next";
import "@/style/index.scss";
import LayoutPage from "@/components/layout/LayoutPage";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutPage>
          <div>{children}</div>
        </LayoutPage>
      </body>
    </html>
  );
}
